export const USER_NAME_MAX_LENGTH = 50;
export const USER_JOB_POSITION_MAX_LENGTH = 100;
export const CHAT_MESSAGE_MAX_LENGTH = 150;
export const GAME_TITLE_MAX_LENGTH = 250;
export const ISSUE_TITLE_MAX_LENGTH = 50;
export const SCORE_TYPE_MAX_LENGTH = 50;
